{% set version = "0.3.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-colourvalues
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/colourvalues_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/colourvalues/colourvalues_{{ version }}.tar.gz
  sha256: d4f1b092dd7a77e6def82e459dc96b98286e4555046521980739de45ded56a14

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh >=1.72.0_3
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp

test:
  commands:
    - $R -e "library('colourvalues')"           # [not win]
    - "\"%R%\" -e \"library('colourvalues')\""  # [win]

about:
  home: https://symbolixau.github.io/colourvalues/
  license: GPL-3.0-only
  summary: Maps one of the viridis colour palettes, or a user-specified palette to values. Viridis colour maps are created by Stéfan van der Walt and Nathaniel Smith, and were set as the default palette for the 'Python' 'Matplotlib' library <https://matplotlib.org/>. Other palettes available in this library have been derived
    from 'RColorBrewer' <https://CRAN.R-project.org/package=RColorBrewer> and 'colorspace' <https://CRAN.R-project.org/package=colorspace> packages.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: colourvalues
# Type: Package
# Title: Assigns Colours to Values
# Version: 0.3.4
# Date: 2020-03-17
# Authors@R: c( person("David", "Cooley", ,"dcooley@symbolix.com.au", role = c("aut", "cre")) )
# Description: Maps one of the viridis colour palettes, or a user-specified palette to values. Viridis colour maps are created by Stefan van der Walt and Nathaniel Smith, and were set as the default palette for the 'Python' 'Matplotlib' library <https://matplotlib.org/>. Other palettes available in this library have been derived from 'RColorBrewer' <https://CRAN.R-project.org/package=RColorBrewer> and 'colorspace' <https://CRAN.R-project.org/package=colorspace> packages.
# License: GPL-3
# URL: https://symbolixau.github.io/colourvalues/
# BugReports: https://github.com/SymbolixAU/colourvalues/issues
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.3.0)
# SystemRequirements: C++11
# LinkingTo: BH (>= 1.72.0-3), Rcpp
# Imports: graphics, Rcpp
# RoxygenNote: 7.0.2
# Suggests: covr, microbenchmark, scales, testthat, viridisLite
# NeedsCompilation: yes
# Packaged: 2020-03-17 02:37:19 UTC; david
# Author: David Cooley [aut, cre]
# Maintainer: David Cooley <dcooley@symbolix.com.au>
# Repository: CRAN
# Date/Publication: 2020-03-18 07:00:15 UTC
